package com.backoffice.servicios;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.5
 * 2018-06-24T15:13:03.839-03:00
 * Generated source version: 3.0.5
 * 
 */
@WebService(targetNamespace = "http://servicios.backoffice.com/", name = "SOAP")
@XmlSeeAlso({ObjectFactory.class})
public interface SOAP {

    @WebMethod
    @RequestWrapper(localName = "estaAutorizado", targetNamespace = "http://servicios.backoffice.com/", className = "com.backoffice.servicios.EstaAutorizado")
    @ResponseWrapper(localName = "estaAutorizadoResponse", targetNamespace = "http://servicios.backoffice.com/", className = "com.backoffice.servicios.EstaAutorizadoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean estaAutorizado(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
