package services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.5
 * 2018-06-24T20:06:34.821-03:00
 * Generated source version: 3.0.5
 * 
 */
@WebServiceClient(name = "SOAPService", 
                  wsdlLocation = "file:/D:/Uade%202018/Integracion%20de%20aplicaciones%20-%20Ingenieria%20sistemas%20II/turismo-workspace/CICLO_I_BACK_AUTORIZACION/src/CICLO_I.wsdl",
                  targetNamespace = "http://services/") 
public class SOAPService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://services/", "SOAPService");
    public final static QName SOAPPort = new QName("http://services/", "SOAPPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/Uade%202018/Integracion%20de%20aplicaciones%20-%20Ingenieria%20sistemas%20II/turismo-workspace/CICLO_I_BACK_AUTORIZACION/src/CICLO_I.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SOAPService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/Uade%202018/Integracion%20de%20aplicaciones%20-%20Ingenieria%20sistemas%20II/turismo-workspace/CICLO_I_BACK_AUTORIZACION/src/CICLO_I.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SOAPService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SOAPService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SOAPService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SOAPService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SOAPService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SOAPService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns SOAP
     */
    @WebEndpoint(name = "SOAPPort")
    public SOAP getSOAPPort() {
        return super.getPort(SOAPPort, SOAP.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SOAP
     */
    @WebEndpoint(name = "SOAPPort")
    public SOAP getSOAPPort(WebServiceFeature... features) {
        return super.getPort(SOAPPort, SOAP.class, features);
    }

}
