package services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.5
 * 2018-06-24T20:06:34.792-03:00
 * Generated source version: 3.0.5
 * 
 */
@WebService(targetNamespace = "http://services/", name = "SOAP")
@XmlSeeAlso({ObjectFactory.class})
public interface SOAP {

    @WebMethod
    @RequestWrapper(localName = "estaAutorizado", targetNamespace = "http://services/", className = "services.EstaAutorizado")
    @ResponseWrapper(localName = "estaAutorizadoResponse", targetNamespace = "http://services/", className = "services.EstaAutorizadoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean estaAutorizado(
        @WebParam(name = "codEntidad", targetNamespace = "")
        java.lang.String codEntidad
    );
}
